env:
  TERM: xterm-256color

window:
  padding:
    x: 6
    y: 6

  title: Alacritty
  class:
    instance: Alacritty
    general: Alacritty

scrolling:
  history: 100000

#;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_;;#

# Font configuration
font:
  normal: 
    family: FiraCode
    style: 

#  bold:
#    family: Iosevka Nerd Font
#    style: Bold

#  italic:
#    family: Iosevka Nerd Font
#    style: Italic

#  bold_italic:
#    family: Iosevka Nerd

  # Point size
  size: 10

  offset:
    x: 0
    y: 0



draw_bold_text_with_bright_colors: true

# Colors
colors:
  # Default colors
  primary:
    background:        '#011627'
    foreground:        '#acb4c2'
    bright_foreground: '#eeeeee'

  # Cursor colors
  cursor:
    text:   '#080808'
    cursor: '#9ca1aa'

  # Selection colors
  selection:
    text:       '#080808'
    background: '#b2ceee'

  # Normal colors
  normal:
    black:   '#1d3b53'
    red:     '#fc514e'
    green:   '#a1cd5e'
    yellow:  '#e3d18a'
    blue:    '#82aaff'
    magenta: '#c792ea'
    cyan:    '#7fdbca'
    white:   '#a1aab8'

  # Bright colors
  bright:
    black:   '#7c8f8f'
    red:     '#ff5874'
    green:   '#21c7a8'
    yellow:  '#ecc48d'
    blue:    '#82aaff'
    magenta: '#ae81ff'
    cyan:    '#7fdbca'
    white:   '#d6deeb'

# -- Background colors

## background_opacity: 0.8 
## window.opacity: 0.1
## window: opacity: 0.9

window:
  opacity: 0.8

cursor:
  unfocused_hollow: false

key_bindings:
    # (Windows, Linux, and BSD only)
  - { key: V,        mods: Control|Shift, action: Paste            }
  - { key: C,        mods: Control|Shift, action: Copy             }
  - { key: Insert,   mods: Shift,         action: PasteSelection   }
  - { key: U,        mods: Control|Shift, action: ResetFontSize    }
  - { key: K,        mods: Control|Shift, action: IncreaseFontSize }
  - { key: K,        mods: Control|Shift, action: IncreaseFontSize }
  - { key: J,        mods: Control|Shift, action: DecreaseFontSize }
  - { key: Paste,                    action: Paste                            }
  - { key: Copy,                     action: Copy                             }
  - { key: L,         mods: Control, action: ClearLogNotice                   }
  - { key: L,         mods: Control, chars: "\x0c"                            }
  - { key: PageUp,    mods: Shift,   action: ScrollPageUp,   mode: ~Alt       }
  - { key: PageDown,  mods: Shift,   action: ScrollPageDown, mode: ~Alt       }
  - { key: Home,      mods: Shift,   action: ScrollToTop,    mode: ~Alt       }
  - { key: End,       mods: Shift,   action: ScrollToBottom, mode: ~Alt       }
